# Generated by Django 3.2.7 on 2021-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('speciliaze', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('MM', 'MM'), ('IS', 'IS')], max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, default='user.png', null=True, upload_to='users %d/%m/%y')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'ordering': ['FName'],
            },
        ),
    ]
