# Generated by Django 3.2.7 on 2021-09-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
