# Generated by Django 3.2.7 on 2021-09-19 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 9, 19, 4, 58, 23, 78484)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='email', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='phone', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to=''),
        ),
    ]
