# Generated by Django 3.2.7 on 2021-09-19 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20210919_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(blank=True, max_length=50, null=True)),
                ('YourEmail', models.EmailField(blank=True, max_length=70, null=True)),
                ('YourPhone', models.CharField(blank=True, max_length=30, null=True)),
                ('YourMessages', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Problem',
                'ordering': ['YourName'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 9, 20, 1, 35, 10, 364513)),
        ),
    ]
