# Generated by Django 3.2.7 on 2021-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_buyingproducts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingproducts',
            name='Img',
            field=models.ImageField(default='animal7.jpg', upload_to='aniamls %d/%m/%y'),
        ),
    ]
