# Generated by Django 3.2.7 on 2021-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_buyingproducts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingproducts',
            name='Img',
            field=models.ImageField(default='aniamls 10/animal7.jpg', upload_to='aniamls/'),
        ),
    ]
